### ISSUE TITLE
helpers/getIndex does not seem to be "stable"

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-query-logic#33]
I mean stable in the same sense as sort algorithms. I have a collection ordered by name, like this:

- Item 1
- Item 2
- Item 3
- Item 4
- Item 4

if I mutate the first `Item 4` in the list, the real-time `updatedData` hook ends up switching the positions of the items,  pushing the modified `Item 4` to the bottom of the list.

**The order should remain stable since the name didn't change at all.**

The [`helpers/getIndex` function](https://github.com/canjs/can-query-logic/blob/083b4c03517a007a11606f08ba0c3451537c1f3d/src/helpers.js#L53-L80) is returning a different value than the `currentIndex` [computed here](https://github.com/canjs/can-connect/blob/4f284fc8b9026767e7cf0f69968a94319b559f13/real-time/real-time.js#L495) and that triggers the list order changes.

I thought it could be the compare function,  but looking at the code it seems to be stable (it returns 0, if itemA === itemB).

**Comment by justinbmeyer** [comment]
In short, the problem here is that the binary search is looking for the first match.  We probably need `compare` here:

https://github.com/canjs/can-query-logic/blob/e9ed9e49a197cf28cae5720039ffe20fbf157fa6/src/helpers.js#L71

to be a bit fuzzier when an exact match is made.  `compare()` might even need to take the array of items and some bounds to check if a match for the identity exists.
